version: '3.8'

services:

# mount/overwrite local copy of code/repo baked into image with live state of the code without need to rebuild image
  indexer:
    # build: # build the image not from GitHub but from local code (required when changes to dependencies were made)
    #   args:
    #     CODE_ORIGIN: copy_local
    volumes:
      - ../:/onto-search

  api:
    # build: # build the image not from GitHub but from local code (required when changes to dependencies were made)
    #   args:
    #     CODE_ORIGIN: copy_local
    volumes:
      - ../:/onto-search

  weaviate-gui:
    profiles: [serve-api]
    # image: naaive/weaviate-ui:latest
    image: jjauthor/weaviate-ui:node-20-bullseye
    ports: 
      - "${WEAVIATE_GUI_EXPOSED_PORT:-127.0.0.1:7777}:7777" # only expose for debugging purposes !!!
    environment:
      WEAVIATE_URL: http://weaviate:8080
      # WEAVIATE_API_KEYS: secret
    depends_on: 
      - weaviate
    restart: on-failure:3

  api-calls:
    profiles: [serve-api]
    build:
      context: ../
      dockerfile: docker-compose-setup/Dockerfile
      args:
        CODE_ORIGIN: copy_local
    environment:
      SEARCH_API_BASE_URI: 127.0.0.1:8014
    network_mode: "service:api"
    depends_on: 
      - api
    volumes:
      - ../:/onto-search
    command: >
      /bin/bash -c "source activate onto_search_env && sleep 10 && python API_calls.py"

  manual-checks-dummy:
    profiles: [indexing, serve-api]
    build:
      context: ../
      dockerfile: docker-compose-setup/Dockerfile
      args:
        CODE_ORIGIN: copy_local
    # environment:
    #   WEAVIATE_PORT: ${WEAVIATE_PORT}
    #   WEAVIATE_PORT_GRPC: ${WEAVIATE_PORT_GRPC}
    command: >
      /bin/bash -c "env && source activate onto_search_env && env && sleep infinity"
