version: '3.8'

services:

# mount/overwrite local copy of code/repo baked into image with live state of the code without need to rebuild image
  indexer:
    build:
      args:
        CODE_ORIGIN: copy_local
    volumes:
      - ../:/onto-search
  api:
    build:
      args:
        CODE_ORIGIN: copy_local
    volumes:
      - ../:/onto-search
    
  weaviate-gui:
    profiles: [indexing, serve-api]
    image: naaive/weaviate-ui:latest
    ports: 
      - "${WEAVIATE_GUI_EXPOSED_PORT:-127.0.0.1:7777}:7777" # only expose for debugging purposes !!!
    environment:
      WEAVIATE_URL: http://weaviate:8080
      # WEAVIATE_API_KEYS: secret

  manual-checks-dummy:
    build:
      context: ../
      dockerfile: docker-compose-setup/Dockerfile
      args:
        CODE_ORIGIN: copy_local
    network_mode: "service:weaviate"
    environment:
      WEAVIATE_PORT: ${WEAVIATE_PORT}
      WEAVIATE_PORT_GRPC: ${WEAVIATE_PORT_GRPC}
    command: >
      /bin/bash -c "source activate onto_search_env && env && sleep infinity"
