version: '3.8'

services:

# mount/overwrite local copy of code/repo baked into image with live state of the code without need to rebuild image
  indexer:
    build:
      args:
        CODE_ORIGIN: copy_local
    volumes:
      - ../:/onto-search
  api:
    build:
      args:
        CODE_ORIGIN: copy_local
    volumes:
      - ../:/onto-search
    
  manual-checks-dummy:
    build:
      context: ../
      dockerfile: docker-compose-setup/Dockerfile
      args:
        CODE_ORIGIN: copy_local
    network_mode: "service:weaviate"
    environment:
      WEAVIATE_PORT: ${WEAVIATE_PORT}
      WEAVIATE_PORT_GRPC: ${WEAVIATE_PORT_GRPC}
    command: >
      /bin/bash -c "source activate onto_search_env && env && sleep infinity"
